<?xml version="1.0" encoding="utf-8"?>
<!-- generator="Joomla! 1.5 - Open Source Content Management" -->
<feed xmlns="http://www.w3.org/2005/Atom"  xml:lang="pt-br">
	<title type="text">Inicio</title>
	<subtitle type="text">Movimento Hermes</subtitle>
	<link rel="alternate" type="text/html" href="http://www.movimentohermes.com.br"/>
	<id>http://www.movimentohermes.com.br/index.php</id>
	<updated>2010-12-05T13:50:24Z</updated>
	<generator uri="http://joomla.org" version="1.5">Joomla! 1.5 - Open Source Content Management</generator>
<link rel="self" type="application/atom+xml" href="http://www.movimentohermes.com.br/index.php?format=feed&amp;type=atom" />
	<entry>
		<title>O que já fizemos pelo CEUE em 2009~2010</title>
		<link rel="alternate" type="text/html" href="http://www.movimentohermes.com.br/component/content/article/o-que-ja-fizemos-pelo-ceue-em-20092010.html"/>
		<published>2010-12-01T04:09:41Z</published>
		<updated>2010-12-01T04:09:41Z</updated>
		<id>http://www.movimentohermes.com.br/component/content/article/o-que-ja-fizemos-pelo-ceue-em-20092010.html</id>
		<author>
			<name>Administrator</name>
		<email>emerson@webdesign.eng.br</email>
		</author>
		<summary type="html">&lt;div align=&quot;center&quot;&gt;&lt;object width=&quot;600&quot; height=&quot;360&quot;&gt;&lt;param name=&quot;movie&quot; value=&quot;http://www.youtube.com/v/qvTyRdRHjJw?fs=1&amp;amp;hl=pt_BR&amp;amp;color1=0x006699&amp;amp;color2=0x54abd6&quot;&gt;&lt;/param&gt;&lt;param name=&quot;allowFullScreen&quot; value=&quot;true&quot;&gt;&lt;/param&gt;&lt;param name=&quot;allowscriptaccess&quot; value=&quot;always&quot;&gt;&lt;/param&gt;&lt;embed src=&quot;http://www.youtube.com/v/qvTyRdRHjJw?fs=1&amp;amp;hl=pt_BR&amp;amp;color1=0x006699&amp;amp;color2=0x54abd6&quot; type=&quot;application/x-shockwave-flash&quot; allowscriptaccess=&quot;always&quot; allowfullscreen=&quot;true&quot; width=&quot;600&quot; height=&quot;360&quot;&gt;&lt;/embed&gt;&lt;/object&gt;&lt;/div&gt;
&lt;p&gt;&lt;/p&gt;
&lt;p&gt; Comprove você mesmo que as ações ditas no video e outras mais realmente ocorreram feitas pela Hermes:&lt;br /&gt;
&lt;a href=&quot;http://www.movimentohermes.com.br/acoes/realizadas.html&quot; target=&quot;_blank&quot;&gt;http://www.movimentohermes.com.br/acoes/realizadas.html&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Para uma visão geral de todos os projetos, veja &lt;a href=&quot;http://www.movimentohermes.com.br/tudo&quot; target=&quot;_blank&quot;&gt;http://www.movimentohermes.com.br/tudo&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;</summary>
		<content type="html">&lt;div align=&quot;center&quot;&gt;&lt;object width=&quot;600&quot; height=&quot;360&quot;&gt;&lt;param name=&quot;movie&quot; value=&quot;http://www.youtube.com/v/qvTyRdRHjJw?fs=1&amp;amp;hl=pt_BR&amp;amp;color1=0x006699&amp;amp;color2=0x54abd6&quot;&gt;&lt;/param&gt;&lt;param name=&quot;allowFullScreen&quot; value=&quot;true&quot;&gt;&lt;/param&gt;&lt;param name=&quot;allowscriptaccess&quot; value=&quot;always&quot;&gt;&lt;/param&gt;&lt;embed src=&quot;http://www.youtube.com/v/qvTyRdRHjJw?fs=1&amp;amp;hl=pt_BR&amp;amp;color1=0x006699&amp;amp;color2=0x54abd6&quot; type=&quot;application/x-shockwave-flash&quot; allowscriptaccess=&quot;always&quot; allowfullscreen=&quot;true&quot; width=&quot;600&quot; height=&quot;360&quot;&gt;&lt;/embed&gt;&lt;/object&gt;&lt;/div&gt;
&lt;p&gt;&lt;/p&gt;
&lt;p&gt; Comprove você mesmo que as ações ditas no video e outras mais realmente ocorreram feitas pela Hermes:&lt;br /&gt;
&lt;a href=&quot;http://www.movimentohermes.com.br/acoes/realizadas.html&quot; target=&quot;_blank&quot;&gt;http://www.movimentohermes.com.br/acoes/realizadas.html&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Para uma visão geral de todos os projetos, veja &lt;a href=&quot;http://www.movimentohermes.com.br/tudo&quot; target=&quot;_blank&quot;&gt;http://www.movimentohermes.com.br/tudo&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;</content>
	</entry>
	<entry>
		<title>Resumo das ações de do Movimento Hermes na Escola de Engenharia</title>
		<link rel="alternate" type="text/html" href="http://www.movimentohermes.com.br/projetos/resumo-das-acoes-de-do-movimento-hermes-na-escola-de-engenharia.html"/>
		<published>2010-11-12T10:44:43Z</published>
		<updated>2010-11-12T10:44:43Z</updated>
		<id>http://www.movimentohermes.com.br/projetos/resumo-das-acoes-de-do-movimento-hermes-na-escola-de-engenharia.html</id>
		<author>
			<name>Administrator</name>
		<email>emerson@webdesign.eng.br</email>
		</author>
		<summary type="html">&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=mhee&quot; target=&quot;_blank&quot;&gt;#mhee&lt;/a&gt;] Resumo das ações de do Movimento Hermes na Escola de Engenharia&lt;/h3&gt;
&lt;h2&gt;Diretoria Acadêmica&lt;/h2&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=saieng&quot; target=&quot;_blank&quot;&gt;#saieng&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/semana-academica-integrada-da-engenharia.html&quot;&gt;Semana Acadêmica Integrada da Engenharia&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Em parceria com subcentros, dar suporte total para organização da semana acadêmica de cada um, além de viabilizar palestras ou outros eventos genéricos, interessantes a qualquer engenharia, e divulgar de forma fácil todos os eventos, mantendo um calendário único de divulgação das atividades.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=pameng&quot; target=&quot;_blank&quot;&gt;#pameng&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/programa-de-apoio-a-mobilidade-entre-engenharias.html&quot;&gt;Programa de apoio a mobilidade entre Engenharias&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Catalogar e divulgar o que já existe para troca de alunos interessados em trocar de curso entre engenharias e, em um segundo momento, viabilizar uma facilitação disto, além de integrar um programa de conscientização da função de cada engenharia.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=gruposdeestudoceue&quot; target=&quot;_blank&quot;&gt;#gruposdeestudoceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/grupos-de-estudos-ceue.html&quot; target=&quot;_blank&quot;&gt;Grupos de Estudos CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Usar salas de aulas ociosas da Escola de Engenharia  em tarde/noites anteriores de certas disciplinas comuns na engenharia (e as com maior indice de repetencia) para estimular a formação de &lt;strong&gt;grupos de estudo&lt;/strong&gt; de alunos interessados, com apoio de material de suporte (listas de excercicios, livros, provas anteriores...), ajuda de colaboradores espontâneos e, ainda que seja fácil conseguir ajuda dos monitores das disciplinas, focar em grupos de estudo, não monitoria.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=feeng&quot; target=&quot;_blank&quot;&gt;#feeng&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/fomento-a-encontro-de-estudantes-de-engenharia.html&quot; target=&quot;_blank&quot;&gt;Fomento a encontro de estudantes de engenharia&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Viabilizar, através de organização interna e catalogação destas informações, encontro de estudantes regionais ou nacionais, bem como facilitar o transporte a estes eventos quando não forem em Porto Alegre.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=rdceue&quot; target=&quot;_blank&quot;&gt;#rdceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/rodada-de-debates.html&quot;&gt;Rodada de debates do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Como forma de incitar os alunos a debaterem sobre assuntos correntes em engenharia, a rodada de debates tem como objetivo trazer atualidades da engenharia, fazer os alunos trabalharem sua comunicação e, consequentemente, melhor sua forma de agir em grupo.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceueajudaaescolherteucurso&quot; target=&quot;_blank&quot;&gt;#ceuemelhoriadelaboratorios]&lt;/a&gt; &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/apoio-a-criacao-e-modernizacao-de-laboratorios.html&quot; target=&quot;_blank&quot;&gt;Apoio a criação e modernização de laboratórios&lt;/a&gt;&lt;a href=&quot;http://www.movimentohermes.com.br/projetos/apoio-a-criacao-e-modernizacao-de-laboratorios.html&quot; target=&quot;_blank&quot;&gt;&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;É de grande importância ter bons laboratórios na engenharia. Trazendo um pensamento antigo, recorrente do início da Escola de Engenharia, visamos a melhoria e a criação de novos laboratórios para a engenharia, por meio de parcerias internas pela alocação de recursos da UFRGs e por parcerias externas, na montagem de laboratórios profissionais.&lt;/p&gt;
&lt;h2&gt;Diretoria de Integração&lt;/h2&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=recepcaodosbixosdaee&quot; target=&quot;_blank&quot;&gt;#recepcaodosbixosdaee&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/recepcao-dos-calouros-da-escola-de-engenharia.html&quot; target=&quot;_blank&quot;&gt;Recepção dos Calouros da Escola de Engenharia&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Receber e dar todo o suporte aos novos alunos da Escola de Engenharia, instruindo sobre moradia, festas, escolha das disciplinas e outras informações básicas para a sobrevivência na UFRGS.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceueteintegra&quot; target=&quot;_blank&quot;&gt;#ceueteintegra&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-te-integra.html&quot;&gt;CEUE Te Integra&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Reúne ações referentes a integração das pessoas. Campeonatos, festas, manutenção e melhoramento da sala de jogos, e afins.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceuerockfestival&quot; target=&quot;_blank&quot;&gt;#ceuerockfestival&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-rock-festival.html&quot;&gt;CEUE Rock Festival&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Circuito de festas com intuito de abrir espaço para as bandas formadas na universidade, culminando no vendo do prêmio Engenharia Rocks!&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=olimpiadassedencatiasceue&quot; target=&quot;_blank&quot;&gt;#olimpiadassedencatiasceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/olimpiadas-sedentarias-do-ceue.html&quot;&gt;Olimpíadas sedentárias do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Continuação das tradicionais Olimpíadas Sedentárias do CEUE, aonde esportes sedentáriamente olímpicos são praticados! Desde sinuca ao às extremamente agitado ping-pong!&lt;/p&gt;
&lt;h2&gt;Diretoria de Marketing e Relações Institucionais&lt;/h2&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceueapoiateusubcentro&quot; target=&quot;_blank&quot;&gt;#ceueapoiateusubcentro&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-apoia-teu-subcentro.html&quot;&gt;CEUE Apoia Teu Subcentro&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Colaborar e integrar ações úteis aos subcentros. É extremamente vital que, além de trabalhar para os estudantes, o CEUE esteja a serviço dos Subcentros em colaboração constante.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=gcmeengbr&quot; target=&quot;_blank&quot;&gt;#gcmeengbr&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/gerenciamento-de-contatos-com-cas-e-das-de-engenharia-do-brasil.html&quot;&gt;Gerenciamento de contatos com CAs e DAs de Engenharia do Brasil&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Descobrir, catalogar e divulgar dados de contato de centros e diretórios acadêmicos de engenharias do Brasil, de modo a servir de suporte a facilitação de troca de informações e ajudas entre o movimento estudantil, e viabilizar outros projetos com maior facilidade, como os encontros de estudantes.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceueteemprega&quot; target=&quot;_blank&quot;&gt;#ceueteemprega&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-te-emprega.html&quot;&gt;CEUE Te Emprega&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Obter e divulgar empregos, estágios, concursos públicos e bolsas para alunos e ex-alunos da Escola de Engenharia.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=riisceue&quot; target=&quot;_blank&quot;&gt;#riisceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/relacoes-institucionais-industriais-e-sindicais-do-ceue.html&quot; target=&quot;_blank&quot;&gt;Relações Institucionais, Industriais e Sindicais do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Manter e cultivar uma boa relação com entidades inter-dependentes da formação em engenharia, com objetivo de viabilizar os projetos e as ações que estamos propondo.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceueajudaaescolherteucurso&quot; target=&quot;_blank&quot;&gt;#ceueajudaaescolherteucurso&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-ajuda-a-escolher-teu-curso.html&quot; target=&quot;_blank&quot;&gt;CEUE ajuda a escolher teu curso&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Projeto de extensão que visa divulgar o que é engenharia, diferenças para os demais   cursos, e para os respectivos cursos, como meio de fomentar a entrada de   alunos conscientes do que querem escolher no vestibular.  Por meios de visitas e palestras para alunos de ensino médio e profissionalizante, conscientizar a profissão também dentro da própria universidade, como parte do &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/programa-de-apoio-a-mobilidade-entre-engenharias.html&quot;&gt;Programa de apoio a mobilidade entre Engenharias&lt;/a&gt;.&lt;/p&gt;
&lt;h2&gt;Diretoria Social&lt;/h2&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceueapoiatuamoradia&quot; target=&quot;_blank&quot;&gt;#ceueapoiatuamoradia&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-apoia-tua-moradia.html&quot;&gt;CEUE apóia tua moradia&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Projeto que visa divulgar, em especial aos calouros, diversas possibilidades de moradia e colaborar para facilitar a moradia em conjunto com colegas, além de ver meios de logística e provável apoio financeiro de colaboradores para custear a manutenção de casas de estudantes sem fins lucrativos aonde alunos da escola de engenharia estiverem (CEUPA, CEUACA, JUC7 e afins).&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=republicadoceue&quot; target=&quot;_blank&quot;&gt;#republicadoceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/republica-do-ceue.html&quot; target=&quot;_blank&quot;&gt;República do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Fomentar a criação de uma república de estudantes da Escola de Engenharia, gerenciada pelos moradores, quer seja em primeiro momento através de espaço físico alugado ou comprado, quer seja mais tarde em realmente trabalhar para contruir do zero um prédio.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=rpee&quot; target=&quot;_blank&quot;&gt;#rpee&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/resgate-do-passado-da-escola-de-engenhariaresgate-do-passado-da-escola-de-engenharia.html&quot; target=&quot;_blank&quot;&gt;Resgate do Passado da Escola de Engenharia&lt;/a&gt;&lt;/h3&gt;
&lt;p&gt;Descobrir, catalogar e divulgar amplamente o passado da Escola de Engenharia e do CEUE, para dar base aos estudantes, professores e servidores de hoje de onde viemos, e, com respeito ao passado, se perguntar: para aonde queremos ir?&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=csaee&quot; target=&quot;_blank&quot;&gt;#csaee&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/conscientizacao-social-de-alunos-da-escola-de-engenharia.html&quot; target=&quot;_blank&quot;&gt;Conscientização Social de Alunos da Escola de Engenharia&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Reunir ações de fomento a conscientização social dos estudantes, em respeito a sociedade em que vivemos.&lt;/p&gt;
&lt;h2&gt;Diretoria de Projetos&lt;/h2&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=apceue&quot; target=&quot;_blank&quot;&gt;#apceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/apoio-a-novos-projetos-do-ceue.html&quot; target=&quot;_blank&quot;&gt;Apoio a novos projetos do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Reunir um modo de agir padrão para apoiar qualquer novo projeto, de modo que qualquer nova ação tenha apoio para viabilidade prática e financeira, além de ser encaminhada para demais pessoas interessadas para sua realização.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=oficinadeprojetos&quot; target=&quot;_blank&quot;&gt;#oficinadeprojetos&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/oficina-de-projetos.html&quot; target=&quot;_blank&quot;&gt;Oficina de Projetos&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Prover meios de a criatividade dos estudantes, em especial de exatas da UFRGS, com apoio, mas não sob direção de professores, tenham infraestrutura, ferramentas e algum apoio financeiro contrução de protótipos, além de promover uma estreita relação entre o mercado de trabalho com o que é desenvolvido na Oficina de Projetos, como meio de dar visibilidade aos participantes e garantir-lhes que, com boas ideias, seu emprego estará garantido antes mesmo de se formar.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=%E2%8C%A9=pt&amp;tag=fliperamanoceue&quot; target=&quot;_blank&quot;&gt;#fliperamanoceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/fliperama-no-ceue.html&quot; target=&quot;_blank&quot;&gt;Fliperama no CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Criar do zero, por esforços dos próprios estudantes da Escola de Engenharia, um Fliperama, tanto como estimulo a criatividade, como para a diversão dos alunos que frequentam o CEUE.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=dsceue&quot; target=&quot;_blank&quot;&gt;#dsceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/desenvolvimento-de-software.html&quot; target=&quot;_blank&quot;&gt;Desenvolvimento de Software do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Tendo em vista que o programa da Hermes é focado no gerenciamento de informações, este projeto visa reunir ações para desenvolvimento de tecnologia própria para organização destas ações.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=graficadoceue&quot; target=&quot;_blank&quot;&gt;#graficadoceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/grafica-do-ceue.html&quot;&gt;Gráfica do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Reativar a histórica gráfica do CEUE, para servir tanto como fonte de renda, como uma importante aliada aos interesses da entidade, focada na utilidade junto aos estudantes de engenharia e da própria UFRGS, porém de modo que fique sob direção do CEUE, para sempre.&lt;/p&gt;
&lt;h2&gt;Secretaria Unificada&lt;/h2&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=frceue&quot; target=&quot;_blank&quot;&gt;#frceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/fontes-de-renda-do-ceue.html&quot;&gt;Fontes de Renda do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Otimizar as fontes de rendas existentes, e procurar novas fontes, focado em desonerar ao máximo o próprio estudante da Escola de Engenharia, e viabilizar que tais retornos além de financeiros a entidade, sejam obtidos por ações que gerem conhecimento e experiência técnica aos participantes, util mais tarde na vida profissional.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=rgceue&quot; target=&quot;_blank&quot;&gt;#rgceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/relatorias-de-gestao-do-ceue.html&quot;&gt;Relatorias de Gestão do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p&gt;Como meio de tornar claro o processo de gestão, as relatorias são a forma mais precisa de que os estudantes estejam inteirados do que está acontecendo em seu Centro Acadêmico.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=gpsceue&quot; target=&quot;_blank&quot;&gt;#gpsceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/gerenciamento-de-prestadores-de-servico-do-ceue.html&quot; target=&quot;_blank&quot;&gt;Gerenciamento de Prestadores de Serviço do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Gerenciar de forma relativamente publica a relação com prestadores de produtos e serviços, de modo que, pela divulgação e troca de informações com parceiros, sempre tenha-se os mais baratos e eficientes prestadores, e estes, ao verem que ao ser bons prestadores atingem uma rede de compradores maior, melhorem e até barateiem seus preços.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=wikigme&quot; target=&quot;_blank&quot;&gt;#wikigme&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/divulgacao-de-gerenciamento-de-entidades-academicas.html&quot;&gt;Wiki GME: Divulgação de Gerenciamento de Entidades Acadêmicas&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Continuar o bom serviço iniciado na wiki &lt;a href=&quot;http://www.gme.ceue.eng.br/&quot; target=&quot;_blank&quot;&gt;http://www.gme.ceue.eng.br/&lt;/a&gt;, que consistem descobrir, catalogar e divulgar informações de como gerenciar uma entidade acadêmica, com informações de organização interna, de eventos, legislação aplicável, fontes de renda e muito mais. É uma wiki, idealizada e mantida pela Hermes que visa o melhoramento em nível nacional de CAs e DAs, além de garantir que as próximas gestões do CEUE saibam como nós fizemos, e garantir que não haja mais gestões medíocres.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=caee&quot; target=&quot;_blank&quot;&gt;#caee&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/cadastro-dos-alunos-e-ex-alunos-da-escola-de-engenharia.html&quot; target=&quot;_blank&quot;&gt;Cadastro dos Alunos e Ex-alunos da Escola de Engenharia&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Descobrir, catalogar e publicar a lista de ex-alunos da Escola de Engenharia, ver meios de deixar claro aqueles que deixaram sua marca na história e, aos que ainda estão vivos, fomentar encontros de turmas e a criação de um anuário de alunos online.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=gceceue&quot; target=&quot;_blank&quot;&gt;#gceceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/gerenciamento-de-contatos-externos-do-ceue-e-subcentros.html&quot; target=&quot;_blank&quot;&gt;Gerenciamento de Contatos Externos do CEUE e Subcentros&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Obter, catalogar e gerenciar contatos externos e manter uma estreita relação com subcentros, como meio de fomentar a troca de informações, em especial do CEUE para o subcentro. Tais contatos ajudarão desde obtenção de palestrantes para eventos, até mesmo doadores, em especial aqueles que estiverem no cadastro de Alunos e Ex-alunos da Escola de Engenharia gerenciado pelo CEUE.&lt;/p&gt;
&lt;h2&gt;Presidência&lt;/h2&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceuepvp&quot; target=&quot;_blank&quot;&gt;#ceuepvp&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-pre-vestibular-popular.html&quot;&gt;CEUE Pré-vestibular Popular&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Através da experiência em 2009, otimizar o funcionamento do Pré-vestibular mantido pelo CEUE, e atacar de forma incisiva os maisores problemas, em especial a confecção de material didático, a falta de professores e afins.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceueatpvp&quot; target=&quot;_blank&quot;&gt;#ceueatpvp&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-apoia-teu-pre-vestibular-popular.html&quot;&gt;CEUE Apoia Teu Pré-vestibular Popular&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Usar a mesma lógica aplicada na organização interna do CEUE Pré-vestibular para, em parceria com outros pré-vestibulares da região, em especial os vinculados a estudantes da UFRGS, viabilizar meios de ajuda mútua, em especial na padronização de material didárico, divulgação, e fontes de rendas alternativas.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceuepdme&quot; target=&quot;_blank&quot;&gt;#ceuepdme&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-procura-os-direitos-do-movimento-estudantil.html&quot; target=&quot;_blank&quot;&gt;CEUE procura os direitos do Movimento Estudantil&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Ao ser atuante em 2009, a Hermes percebeu que muito se perde ao não se saber seus direitos. Este projeto visa através descobrir até aonde o estudante tem direito frente a professores e a instituições de ensino, além de em especial ver o que centros e diretórios acadêmicos podem fazer e garantir sua autonomia.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=jornaldoceue&quot; target=&quot;_blank&quot;&gt;#jornaldoceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/jornal-do-ceue.html&quot; target=&quot;_blank&quot;&gt;Jornal do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Divulgar as ações tomadas na Escola de Engenharia, novidades no mundo da Engenharia, problemas a serem solucionados e divulgar as ações que estão sendo tomadas em nome doe estudantes.&lt;/p&gt;</summary>
		<content type="html">&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=mhee&quot; target=&quot;_blank&quot;&gt;#mhee&lt;/a&gt;] Resumo das ações de do Movimento Hermes na Escola de Engenharia&lt;/h3&gt;
&lt;h2&gt;Diretoria Acadêmica&lt;/h2&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=saieng&quot; target=&quot;_blank&quot;&gt;#saieng&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/semana-academica-integrada-da-engenharia.html&quot;&gt;Semana Acadêmica Integrada da Engenharia&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Em parceria com subcentros, dar suporte total para organização da semana acadêmica de cada um, além de viabilizar palestras ou outros eventos genéricos, interessantes a qualquer engenharia, e divulgar de forma fácil todos os eventos, mantendo um calendário único de divulgação das atividades.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=pameng&quot; target=&quot;_blank&quot;&gt;#pameng&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/programa-de-apoio-a-mobilidade-entre-engenharias.html&quot;&gt;Programa de apoio a mobilidade entre Engenharias&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Catalogar e divulgar o que já existe para troca de alunos interessados em trocar de curso entre engenharias e, em um segundo momento, viabilizar uma facilitação disto, além de integrar um programa de conscientização da função de cada engenharia.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=gruposdeestudoceue&quot; target=&quot;_blank&quot;&gt;#gruposdeestudoceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/grupos-de-estudos-ceue.html&quot; target=&quot;_blank&quot;&gt;Grupos de Estudos CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Usar salas de aulas ociosas da Escola de Engenharia  em tarde/noites anteriores de certas disciplinas comuns na engenharia (e as com maior indice de repetencia) para estimular a formação de &lt;strong&gt;grupos de estudo&lt;/strong&gt; de alunos interessados, com apoio de material de suporte (listas de excercicios, livros, provas anteriores...), ajuda de colaboradores espontâneos e, ainda que seja fácil conseguir ajuda dos monitores das disciplinas, focar em grupos de estudo, não monitoria.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=feeng&quot; target=&quot;_blank&quot;&gt;#feeng&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/fomento-a-encontro-de-estudantes-de-engenharia.html&quot; target=&quot;_blank&quot;&gt;Fomento a encontro de estudantes de engenharia&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Viabilizar, através de organização interna e catalogação destas informações, encontro de estudantes regionais ou nacionais, bem como facilitar o transporte a estes eventos quando não forem em Porto Alegre.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=rdceue&quot; target=&quot;_blank&quot;&gt;#rdceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/rodada-de-debates.html&quot;&gt;Rodada de debates do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Como forma de incitar os alunos a debaterem sobre assuntos correntes em engenharia, a rodada de debates tem como objetivo trazer atualidades da engenharia, fazer os alunos trabalharem sua comunicação e, consequentemente, melhor sua forma de agir em grupo.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceueajudaaescolherteucurso&quot; target=&quot;_blank&quot;&gt;#ceuemelhoriadelaboratorios]&lt;/a&gt; &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/apoio-a-criacao-e-modernizacao-de-laboratorios.html&quot; target=&quot;_blank&quot;&gt;Apoio a criação e modernização de laboratórios&lt;/a&gt;&lt;a href=&quot;http://www.movimentohermes.com.br/projetos/apoio-a-criacao-e-modernizacao-de-laboratorios.html&quot; target=&quot;_blank&quot;&gt;&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;É de grande importância ter bons laboratórios na engenharia. Trazendo um pensamento antigo, recorrente do início da Escola de Engenharia, visamos a melhoria e a criação de novos laboratórios para a engenharia, por meio de parcerias internas pela alocação de recursos da UFRGs e por parcerias externas, na montagem de laboratórios profissionais.&lt;/p&gt;
&lt;h2&gt;Diretoria de Integração&lt;/h2&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=recepcaodosbixosdaee&quot; target=&quot;_blank&quot;&gt;#recepcaodosbixosdaee&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/recepcao-dos-calouros-da-escola-de-engenharia.html&quot; target=&quot;_blank&quot;&gt;Recepção dos Calouros da Escola de Engenharia&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Receber e dar todo o suporte aos novos alunos da Escola de Engenharia, instruindo sobre moradia, festas, escolha das disciplinas e outras informações básicas para a sobrevivência na UFRGS.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceueteintegra&quot; target=&quot;_blank&quot;&gt;#ceueteintegra&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-te-integra.html&quot;&gt;CEUE Te Integra&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Reúne ações referentes a integração das pessoas. Campeonatos, festas, manutenção e melhoramento da sala de jogos, e afins.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceuerockfestival&quot; target=&quot;_blank&quot;&gt;#ceuerockfestival&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-rock-festival.html&quot;&gt;CEUE Rock Festival&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Circuito de festas com intuito de abrir espaço para as bandas formadas na universidade, culminando no vendo do prêmio Engenharia Rocks!&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=olimpiadassedencatiasceue&quot; target=&quot;_blank&quot;&gt;#olimpiadassedencatiasceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/olimpiadas-sedentarias-do-ceue.html&quot;&gt;Olimpíadas sedentárias do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Continuação das tradicionais Olimpíadas Sedentárias do CEUE, aonde esportes sedentáriamente olímpicos são praticados! Desde sinuca ao às extremamente agitado ping-pong!&lt;/p&gt;
&lt;h2&gt;Diretoria de Marketing e Relações Institucionais&lt;/h2&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceueapoiateusubcentro&quot; target=&quot;_blank&quot;&gt;#ceueapoiateusubcentro&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-apoia-teu-subcentro.html&quot;&gt;CEUE Apoia Teu Subcentro&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Colaborar e integrar ações úteis aos subcentros. É extremamente vital que, além de trabalhar para os estudantes, o CEUE esteja a serviço dos Subcentros em colaboração constante.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=gcmeengbr&quot; target=&quot;_blank&quot;&gt;#gcmeengbr&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/gerenciamento-de-contatos-com-cas-e-das-de-engenharia-do-brasil.html&quot;&gt;Gerenciamento de contatos com CAs e DAs de Engenharia do Brasil&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Descobrir, catalogar e divulgar dados de contato de centros e diretórios acadêmicos de engenharias do Brasil, de modo a servir de suporte a facilitação de troca de informações e ajudas entre o movimento estudantil, e viabilizar outros projetos com maior facilidade, como os encontros de estudantes.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceueteemprega&quot; target=&quot;_blank&quot;&gt;#ceueteemprega&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-te-emprega.html&quot;&gt;CEUE Te Emprega&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Obter e divulgar empregos, estágios, concursos públicos e bolsas para alunos e ex-alunos da Escola de Engenharia.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=riisceue&quot; target=&quot;_blank&quot;&gt;#riisceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/relacoes-institucionais-industriais-e-sindicais-do-ceue.html&quot; target=&quot;_blank&quot;&gt;Relações Institucionais, Industriais e Sindicais do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Manter e cultivar uma boa relação com entidades inter-dependentes da formação em engenharia, com objetivo de viabilizar os projetos e as ações que estamos propondo.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceueajudaaescolherteucurso&quot; target=&quot;_blank&quot;&gt;#ceueajudaaescolherteucurso&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-ajuda-a-escolher-teu-curso.html&quot; target=&quot;_blank&quot;&gt;CEUE ajuda a escolher teu curso&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Projeto de extensão que visa divulgar o que é engenharia, diferenças para os demais   cursos, e para os respectivos cursos, como meio de fomentar a entrada de   alunos conscientes do que querem escolher no vestibular.  Por meios de visitas e palestras para alunos de ensino médio e profissionalizante, conscientizar a profissão também dentro da própria universidade, como parte do &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/programa-de-apoio-a-mobilidade-entre-engenharias.html&quot;&gt;Programa de apoio a mobilidade entre Engenharias&lt;/a&gt;.&lt;/p&gt;
&lt;h2&gt;Diretoria Social&lt;/h2&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceueapoiatuamoradia&quot; target=&quot;_blank&quot;&gt;#ceueapoiatuamoradia&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-apoia-tua-moradia.html&quot;&gt;CEUE apóia tua moradia&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Projeto que visa divulgar, em especial aos calouros, diversas possibilidades de moradia e colaborar para facilitar a moradia em conjunto com colegas, além de ver meios de logística e provável apoio financeiro de colaboradores para custear a manutenção de casas de estudantes sem fins lucrativos aonde alunos da escola de engenharia estiverem (CEUPA, CEUACA, JUC7 e afins).&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=republicadoceue&quot; target=&quot;_blank&quot;&gt;#republicadoceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/republica-do-ceue.html&quot; target=&quot;_blank&quot;&gt;República do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Fomentar a criação de uma república de estudantes da Escola de Engenharia, gerenciada pelos moradores, quer seja em primeiro momento através de espaço físico alugado ou comprado, quer seja mais tarde em realmente trabalhar para contruir do zero um prédio.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=rpee&quot; target=&quot;_blank&quot;&gt;#rpee&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/resgate-do-passado-da-escola-de-engenhariaresgate-do-passado-da-escola-de-engenharia.html&quot; target=&quot;_blank&quot;&gt;Resgate do Passado da Escola de Engenharia&lt;/a&gt;&lt;/h3&gt;
&lt;p&gt;Descobrir, catalogar e divulgar amplamente o passado da Escola de Engenharia e do CEUE, para dar base aos estudantes, professores e servidores de hoje de onde viemos, e, com respeito ao passado, se perguntar: para aonde queremos ir?&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=csaee&quot; target=&quot;_blank&quot;&gt;#csaee&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/conscientizacao-social-de-alunos-da-escola-de-engenharia.html&quot; target=&quot;_blank&quot;&gt;Conscientização Social de Alunos da Escola de Engenharia&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Reunir ações de fomento a conscientização social dos estudantes, em respeito a sociedade em que vivemos.&lt;/p&gt;
&lt;h2&gt;Diretoria de Projetos&lt;/h2&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=apceue&quot; target=&quot;_blank&quot;&gt;#apceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/apoio-a-novos-projetos-do-ceue.html&quot; target=&quot;_blank&quot;&gt;Apoio a novos projetos do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Reunir um modo de agir padrão para apoiar qualquer novo projeto, de modo que qualquer nova ação tenha apoio para viabilidade prática e financeira, além de ser encaminhada para demais pessoas interessadas para sua realização.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=oficinadeprojetos&quot; target=&quot;_blank&quot;&gt;#oficinadeprojetos&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/oficina-de-projetos.html&quot; target=&quot;_blank&quot;&gt;Oficina de Projetos&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Prover meios de a criatividade dos estudantes, em especial de exatas da UFRGS, com apoio, mas não sob direção de professores, tenham infraestrutura, ferramentas e algum apoio financeiro contrução de protótipos, além de promover uma estreita relação entre o mercado de trabalho com o que é desenvolvido na Oficina de Projetos, como meio de dar visibilidade aos participantes e garantir-lhes que, com boas ideias, seu emprego estará garantido antes mesmo de se formar.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=%E2%8C%A9=pt&amp;tag=fliperamanoceue&quot; target=&quot;_blank&quot;&gt;#fliperamanoceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/fliperama-no-ceue.html&quot; target=&quot;_blank&quot;&gt;Fliperama no CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Criar do zero, por esforços dos próprios estudantes da Escola de Engenharia, um Fliperama, tanto como estimulo a criatividade, como para a diversão dos alunos que frequentam o CEUE.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=dsceue&quot; target=&quot;_blank&quot;&gt;#dsceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/desenvolvimento-de-software.html&quot; target=&quot;_blank&quot;&gt;Desenvolvimento de Software do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Tendo em vista que o programa da Hermes é focado no gerenciamento de informações, este projeto visa reunir ações para desenvolvimento de tecnologia própria para organização destas ações.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=graficadoceue&quot; target=&quot;_blank&quot;&gt;#graficadoceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/grafica-do-ceue.html&quot;&gt;Gráfica do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Reativar a histórica gráfica do CEUE, para servir tanto como fonte de renda, como uma importante aliada aos interesses da entidade, focada na utilidade junto aos estudantes de engenharia e da própria UFRGS, porém de modo que fique sob direção do CEUE, para sempre.&lt;/p&gt;
&lt;h2&gt;Secretaria Unificada&lt;/h2&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=frceue&quot; target=&quot;_blank&quot;&gt;#frceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/fontes-de-renda-do-ceue.html&quot;&gt;Fontes de Renda do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Otimizar as fontes de rendas existentes, e procurar novas fontes, focado em desonerar ao máximo o próprio estudante da Escola de Engenharia, e viabilizar que tais retornos além de financeiros a entidade, sejam obtidos por ações que gerem conhecimento e experiência técnica aos participantes, util mais tarde na vida profissional.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=rgceue&quot; target=&quot;_blank&quot;&gt;#rgceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/relatorias-de-gestao-do-ceue.html&quot;&gt;Relatorias de Gestão do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p&gt;Como meio de tornar claro o processo de gestão, as relatorias são a forma mais precisa de que os estudantes estejam inteirados do que está acontecendo em seu Centro Acadêmico.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=gpsceue&quot; target=&quot;_blank&quot;&gt;#gpsceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/gerenciamento-de-prestadores-de-servico-do-ceue.html&quot; target=&quot;_blank&quot;&gt;Gerenciamento de Prestadores de Serviço do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Gerenciar de forma relativamente publica a relação com prestadores de produtos e serviços, de modo que, pela divulgação e troca de informações com parceiros, sempre tenha-se os mais baratos e eficientes prestadores, e estes, ao verem que ao ser bons prestadores atingem uma rede de compradores maior, melhorem e até barateiem seus preços.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=wikigme&quot; target=&quot;_blank&quot;&gt;#wikigme&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/divulgacao-de-gerenciamento-de-entidades-academicas.html&quot;&gt;Wiki GME: Divulgação de Gerenciamento de Entidades Acadêmicas&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Continuar o bom serviço iniciado na wiki &lt;a href=&quot;http://www.gme.ceue.eng.br/&quot; target=&quot;_blank&quot;&gt;http://www.gme.ceue.eng.br/&lt;/a&gt;, que consistem descobrir, catalogar e divulgar informações de como gerenciar uma entidade acadêmica, com informações de organização interna, de eventos, legislação aplicável, fontes de renda e muito mais. É uma wiki, idealizada e mantida pela Hermes que visa o melhoramento em nível nacional de CAs e DAs, além de garantir que as próximas gestões do CEUE saibam como nós fizemos, e garantir que não haja mais gestões medíocres.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=caee&quot; target=&quot;_blank&quot;&gt;#caee&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/cadastro-dos-alunos-e-ex-alunos-da-escola-de-engenharia.html&quot; target=&quot;_blank&quot;&gt;Cadastro dos Alunos e Ex-alunos da Escola de Engenharia&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Descobrir, catalogar e publicar a lista de ex-alunos da Escola de Engenharia, ver meios de deixar claro aqueles que deixaram sua marca na história e, aos que ainda estão vivos, fomentar encontros de turmas e a criação de um anuário de alunos online.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=gceceue&quot; target=&quot;_blank&quot;&gt;#gceceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/gerenciamento-de-contatos-externos-do-ceue-e-subcentros.html&quot; target=&quot;_blank&quot;&gt;Gerenciamento de Contatos Externos do CEUE e Subcentros&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Obter, catalogar e gerenciar contatos externos e manter uma estreita relação com subcentros, como meio de fomentar a troca de informações, em especial do CEUE para o subcentro. Tais contatos ajudarão desde obtenção de palestrantes para eventos, até mesmo doadores, em especial aqueles que estiverem no cadastro de Alunos e Ex-alunos da Escola de Engenharia gerenciado pelo CEUE.&lt;/p&gt;
&lt;h2&gt;Presidência&lt;/h2&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceuepvp&quot; target=&quot;_blank&quot;&gt;#ceuepvp&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-pre-vestibular-popular.html&quot;&gt;CEUE Pré-vestibular Popular&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Através da experiência em 2009, otimizar o funcionamento do Pré-vestibular mantido pelo CEUE, e atacar de forma incisiva os maisores problemas, em especial a confecção de material didático, a falta de professores e afins.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceueatpvp&quot; target=&quot;_blank&quot;&gt;#ceueatpvp&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-apoia-teu-pre-vestibular-popular.html&quot;&gt;CEUE Apoia Teu Pré-vestibular Popular&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Usar a mesma lógica aplicada na organização interna do CEUE Pré-vestibular para, em parceria com outros pré-vestibulares da região, em especial os vinculados a estudantes da UFRGS, viabilizar meios de ajuda mútua, em especial na padronização de material didárico, divulgação, e fontes de rendas alternativas.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=ceuepdme&quot; target=&quot;_blank&quot;&gt;#ceuepdme&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/ceue-procura-os-direitos-do-movimento-estudantil.html&quot; target=&quot;_blank&quot;&gt;CEUE procura os direitos do Movimento Estudantil&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Ao ser atuante em 2009, a Hermes percebeu que muito se perde ao não se saber seus direitos. Este projeto visa através descobrir até aonde o estudante tem direito frente a professores e a instituições de ensino, além de em especial ver o que centros e diretórios acadêmicos podem fazer e garantir sua autonomia.&lt;/p&gt;
&lt;h3&gt;[&lt;a href=&quot;http://search.twitter.com/search?q=&amp;lang=pt&amp;tag=jornaldoceue&quot; target=&quot;_blank&quot;&gt;#jornaldoceue&lt;/a&gt;] &lt;a href=&quot;http://www.movimentohermes.com.br/projetos/jornal-do-ceue.html&quot; target=&quot;_blank&quot;&gt;Jornal do CEUE&lt;/a&gt;&lt;/h3&gt;
&lt;p style=&quot;padding-left: 30px;&quot;&gt;Divulgar as ações tomadas na Escola de Engenharia, novidades no mundo da Engenharia, problemas a serem solucionados e divulgar as ações que estão sendo tomadas em nome doe estudantes.&lt;/p&gt;</content>
	</entry>
</feed>
